blog:
  title_header: "@GillesLegoux (glegoux)"
  title: "Software Engineering"
  keywords: ["Research & Development", "Algorithm", "Data", "Machine Learning", "Web", "Security", "Applied Mathematics", "Reliability & Infrastructure", "Design", "System", "Methodology", "Business"]
google_analytics:
  code: "UA-155162630-1"
disqus_name: "glegoux-com"
